name: Build Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build APK with Gradle
        run: ./gradlew clean app:assembleRelease
        
      - name: Find and list APK files
        run: |
          echo "查找所有APK文件："
          find . -name "*.apk" -type f -exec ls -la {} \;
        
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: "**/build/outputs/apk/release/*.apk"
          retention-days: 30
